Fix docksal deploy scripts (deploy-prod still won't work for now)

diff --git a/.docksal/commands/deploy-prod b/.docksal/commands/deploy-prod
--- a/.docksal/commands/deploy-prod
+++ b/.docksal/commands/deploy-prod
@@ -11,6 +11,13 @@ then
     exit 1
 fi
 
+if [ -z "$PROJECT_ROOT" ]
+then
+    echo "Error: PROJECT_ROOT not defined. Run as 'fin restore-test-db'." >&2
+    echo "Or, if you're not using Docksal, just define PROJECT_ROOT=<dir containing composer.json>" >&2
+    exit 1
+fi
+
 # Identify which branch we're using
 remote=origin
 if [ $# -eq 2 ]
@@ -28,13 +35,14 @@ fi
 
 # Check connection
 echo "Checking that we're good to go..."
-fin check-vpn || exit $?
+"$PROJECT_ROOT"/.docksal/commands/check-vpn || exit $?
 
+drush=$PROJECT_ROOT/vendor/bin/drush
 
 # Put prod in maintenance mode and backup database
 bring_prod_back_online()
 {
-
+    echo "Taking the prod site out of maintenance mode..."
     $drush @self.prod sset system.maintenance_mode FALSE
 }
 
@@ -51,14 +59,19 @@ then
     exit 1
 fi
 
-prod_root=$($drush sa @self.prod --fields=root | grep -oP 'root: \K.*$')
+#prod_root=$($drush sa @self.prod --fields=root | grep -oP 'root: \K.*$')
+prod_root=/home/neuronet/deployments/test_deploy/web
+echo '****************'
+echo "The prod site doesn't have the right directory structure yet, so using a fake one:"
+echo "prod_root=$prod_root"
+echo "After manually updating prod site to composer structure, remove this safety mechanism."
+echo '****************'
+
 
 # Deploy to test site and build
 echo "Deploying $remote/$branch to the test site."
 
-drush=$PROJECT_ROOT/vendor/bin/drush
-
-
+echo 'SSHing to test site...'
 server_code=$(cat << EOF
     cd .. &&
     echo Putting the test site in maintenance mode... &&
@@ -67,7 +80,7 @@ server_code=$(cat << EOF
     echo &&
     echo Checking out branch $remote/$branch... &&
     git fetch $remote &&
-    git checkout --detach $remote/$branch &&
+    git checkout -f $remote/$branch &&
     git reset --hard &&
 
     echo &&
@@ -92,15 +105,17 @@ server_code=$(cat << EOF
     echo Updating prod database... &&
     vendor/bin/drush updb -y &&
 
-    echo 'Prod deployed! Make sure https://www.neuronetupenn.org looks right.' && exit 0
+    echo Prod deployed! Make sure https://www.neuronetupenn.org looks right. && exit 0
     
-    || cd .. &&
+    || echo Error updating database. &&
+    cd $prod_root/.. &&
     rsync -a --delete /home/neuronet/deployments/prod_backup/ . &&
     vendor/bin/drush sql-drop -y &&
     vendor/bin/drush sql-query --file="$prod_dump" &&
-    echo 'Error updating database. Prod files and database restored. &&
+    echo Prod files and database restored.
+    || echo Error restoring prod files and database - must fix manually;
     exit 1
 EOF
 )
 
-$drush @self.test --ssh-options="-t" ssh "sudo -u neuronet bash -c \"$server_code\""
+$drush @self.test --tty ssh "sudo -u neuronet bash -ic '$server_code'"
diff --git a/.docksal/commands/deploy-test b/.docksal/commands/deploy-test
--- a/.docksal/commands/deploy-test
+++ b/.docksal/commands/deploy-test
@@ -14,11 +14,19 @@ then
 	exit 1
 fi
 
+if [ -z "$PROJECT_ROOT" ]
+then
+    echo "Error: PROJECT_ROOT not defined. Run as 'fin restore-test-db'." >&2
+    echo "Or, if you're not using Docksal, just define PROJECT_ROOT=<dir containing composer.json>" >&2
+    exit 1
+fi
+
 branch=$1
 echo "Deploying dev/$branch to the test site."
 
 echo "Checking that we're good to go..."
-fin check-vpn || exit $?
+
+"$PROJECT_ROOT"/.docksal/commands/check-vpn || exit $?
 
 drush=$PROJECT_ROOT/vendor/bin/drush
 
@@ -46,7 +54,7 @@ server_code=$(cat << EOF
 	echo Checking out branch $branch... &&
 	cd .. &&
 	git fetch dev &&
-	git checkout --detach dev/$branch &&
+	git checkout -f dev/$branch &&
 	git reset --hard &&
 
 	echo &&
@@ -69,4 +77,4 @@ server_code=$(cat << EOF
 EOF
 )
 
-$drush @self.test --ssh-options="-t" ssh "sudo -u neuronet bash \"$server_code\""
+$drush @self.test --tty ssh "sudo -u neuronet bash -ic '$server_code'"
diff --git a/.docksal/commands/restore-test-db b/.docksal/commands/restore-test-db
--- a/.docksal/commands/restore-test-db
+++ b/.docksal/commands/restore-test-db
@@ -2,29 +2,44 @@
 
 # Restores the latest test DB dump to the test site, and updates it if necessary
 echo "Checking that we're good to go..."
-fin check-vpn || exit $?
+
+if [ -z "$PROJECT_ROOT" ]
+then
+    echo "Error: PROJECT_ROOT not defined. Run as 'fin restore-test-db'." >&2
+    echo "Or, if you're not using Docksal, just define PROJECT_ROOT=<dir containing composer.json>" >&2
+    exit 1
+fi
+
+"$PROJECT_ROOT"/.docksal/commands/check-vpn || exit $?
 
 drush=$PROJECT_ROOT/vendor/bin/drush
 
 
 # use some command-fu to find and restore the newest test dump
-# have to use semicolons because drush ssh is dumb
+# have to make it all one bash "list" b/c drush ssh is dumb
+# Can't use single quotes, that would be too many layers
 server_code=$(cat << 'EOF'
-    latest_dump=$(echo $HOME/backups/test_*.sql | tr ' ' '\n' | tail -n 1) &&
+    cd .. &&
+    latest_dump=$(echo $HOME/backups/test_*.sql | tr " " "\n" | tail -n 1) &&
     if [ -z $latest_dump ];
     then
         touch foo;
-        echo 'No test database dump to restore' >&2;
+        echo No test database dump to restore >&2;
         exit 1;
     fi &&
 
     echo Restoring $latest_dump to test DB &&
-    drush=../vendor/bin/drush &&
+    drush=vendor/bin/drush &&
     $drush sset system.maintenance_mode TRUE &&
-    $drush sql-drop &&
-    $drush sql-query --file=$latest_dump &&
+    echo Turned on maintenance mode &&
+    $drush sql-drop -y &&
+    echo Dropped current test database &&
+    $drush sql-query --file="$latest_dump" &&
+    echo Restored "$latest_dump" &&
     $drush updb -y &&
+    echo Updated databse &&
     $drush sset system.maintenance_mode FALSE &&
+    echo Turned off maintenance mode &&
     echo &&
     echo Test DB restored.
 
@@ -34,4 +49,4 @@ EOF
 
 # ssh_cmd=(bash +O nullglob -c "$server_code")
 # $drush @self.test --tty ssh "${ssh_cmd[*]}"
-$drush @self.test --ssh-options="-t" ssh "sudo -u neuronet bash +O nullglob -c \"$server_code\""
+$drush @self.test --tty ssh "sudo -u neuronet bash +O nullglob -ic '$server_code'"
